CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(150) unique NOT NULL,
  name VARCHAR(50) NOT NULL,
  password BINARY(32) NOT NULL,
  salt BINARY(32) NOT NULL,
  authenticated BOOLEAN,
  registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_access TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);